global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.31.9.253:9100']
        labels:
          instance: 'recheck-app'

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.31.9.253:8080']
        labels:
          instance: 'recheck-app'